import type { CaseStudy } from './dolMotor';
import { dolMotorCase } from './dolMotor';

export const starDeltaCase: CaseStudy = {
  id: 'star_delta',
  title: 'Star-Delta Starter',
  description: 'Star-Delta starter digunakan untuk mengurangi arus starting motor 3-phase. Motor dimulai dalam konfigurasi star, kemudian beralih ke delta setelah kecepatan tertentu.',
  ioAssignment: [
    { type: 'input', address: 'I0.0', label: 'Start Button' },
    { type: 'input', address: 'I0.1', label: 'Stop Button' },
    { type: 'output', address: 'Q0.0', label: 'Main Contactor' },
    { type: 'output', address: 'Q0.1', label: 'Star Contactor' },
    { type: 'output', address: 'Q0.2', label: 'Delta Contactor' },
    { type: 'output', address: 'Q0.3', label: 'Timer Indicator' },
  ],
  questions: [
    {
      id: 'sd_q1',
      title: 'Main Contactor',
      description: 'Buat ladder untuk mengaktifkan main contactor (Q0.0) dengan start/stop dan latch.',
      hint: 'Gunakan konfigurasi start-stop-latch dasar',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 3 },
      ],
      maxRungs: 1,
    },
    {
      id: 'sd_q2',
      title: 'Timer untuk Switching',
      description: 'Tambahkan timer TON (T0) yang aktif saat main contactor ON.',
      hint: 'Kontak Q0.0 mengaktifkan timer T0',
      expectedAnswer: [
        { type: 'contact_no', address: 'Q0.0', rung: 1, position: 0 },
        { type: 'timer_ton', address: 'T0', rung: 1, position: 1 },
      ],
      maxRungs: 2,
    },
    {
      id: 'sd_q3',
      title: 'Star Contactor',
      description: 'Star contactor (Q0.1) aktif saat timer belum done. Gunakan kontak NC timer.',
      hint: 'Kontak NC (T0) mengaktifkan Q0.1',
      expectedAnswer: [
        { type: 'contact_no', address: 'Q0.0', rung: 2, position: 0 },
        { type: 'contact_nc', address: 'T0', rung: 2, position: 1 },
        { type: 'coil', address: 'Q0.1', rung: 2, position: 2 },
      ],
      maxRungs: 3,
    },
    {
      id: 'sd_q4',
      title: 'Delta Contactor',
      description: 'Delta contactor (Q0.2) aktif saat timer done. Gunakan kontak NO timer.',
      hint: 'Kontak NO (T0) mengaktifkan Q0.2',
      expectedAnswer: [
        { type: 'contact_no', address: 'Q0.0', rung: 3, position: 0 },
        { type: 'contact_no', address: 'T0', rung: 3, position: 1 },
        { type: 'coil', address: 'Q0.2', rung: 3, position: 2 },
      ],
      maxRungs: 3,
    },
    {
      id: 'sd_q5',
      title: 'Interlock Star-Delta',
      description: 'Pastikan star (Q0.1) dan delta (Q0.2) tidak aktif bersamaan. Tambahkan interlock.',
      hint: 'Tambahkan kontak NC Q0.2 di rung star, dan kontak NC Q0.1 di rung delta',
      expectedAnswer: [
        { type: 'contact_no', address: 'Q0.0', rung: 2, position: 0 },
        { type: 'contact_nc', address: 'T0', rung: 2, position: 1 },
        { type: 'contact_nc', address: 'Q0.2', rung: 2, position: 2 },
        { type: 'coil', address: 'Q0.1', rung: 2, position: 3 },
      ],
      maxRungs: 3,
    },
    {
      id: 'sd_q6',
      title: 'Timer Indicator',
      description: 'Tambahkan indikator (Q0.3) yang menyala saat timer counting.',
      hint: 'Gunakan kontak NC (T0) untuk indicator',
      expectedAnswer: [
        { type: 'contact_nc', address: 'T0', rung: 4, position: 0 },
        { type: 'coil', address: 'Q0.3', rung: 4, position: 1 },
      ],
      maxRungs: 4,
    },
    {
      id: 'sd_q7',
      title: 'Analisis Rung',
      description: 'Apa yang terjadi jika interlock tidak dipasang?',
      hint: 'Star dan delta bisa aktif bersamaan menyebabkan short circuit',
      expectedAnswer: [
        { type: 'contact_no', address: 'Q0.0', rung: 2, position: 0 },
        { type: 'contact_nc', address: 'T0', rung: 2, position: 1 },
        { type: 'coil', address: 'Q0.1', rung: 2, position: 2 },
      ],
      maxRungs: 2,
    },
    {
      id: 'sd_q8',
      title: 'Stop Semua Contactor',
      description: 'Pastikan semua contactor mati saat stop (I0.1) ditekan.',
      hint: 'Stop button (I0.1) memutus main contactor Q0.0',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 3 },
      ],
      maxRungs: 1,
    },
    {
      id: 'sd_q9',
      title: 'Delay Transition',
      description: 'Ubah timer menjadi 10 detik. Bagaimana pengaruhnya terhadap ladder?',
      hint: 'Struktur ladder sama, hanya preset timer yang berubah',
      expectedAnswer: [
        { type: 'contact_no', address: 'Q0.0', rung: 1, position: 0 },
        { type: 'timer_ton', address: 'T0', rung: 1, position: 1 },
      ],
      maxRungs: 2,
    },
    {
      id: 'sd_q10',
      title: 'Full Star-Delta Circuit',
      description: 'Buat ladder lengkap: main contactor, timer, star dengan interlock, delta dengan interlock.',
      hint: 'Gabungkan semua: Q0.0 (main), T0 (timer), Q0.1 (star + interlock Q0.2), Q0.2 (delta + interlock Q0.1)',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 3 },
        { type: 'contact_no', address: 'Q0.0', rung: 1, position: 0 },
        { type: 'timer_ton', address: 'T0', rung: 1, position: 1 },
        { type: 'contact_no', address: 'Q0.0', rung: 2, position: 0 },
        { type: 'contact_nc', address: 'T0', rung: 2, position: 1 },
        { type: 'contact_nc', address: 'Q0.2', rung: 2, position: 2 },
        { type: 'coil', address: 'Q0.1', rung: 2, position: 3 },
        { type: 'contact_no', address: 'Q0.0', rung: 3, position: 0 },
        { type: 'contact_no', address: 'T0', rung: 3, position: 1 },
        { type: 'contact_nc', address: 'Q0.1', rung: 3, position: 2 },
        { type: 'coil', address: 'Q0.2', rung: 3, position: 3 },
      ],
      maxRungs: 4,
    },
  ],
};

export const trafficLightCase: CaseStudy = {
  id: 'traffic_light',
  title: 'Traffic Light Control',
  description: 'Sistem lampu lalu lintas dengan sequencer otomatis. Pelajari sequential control dan timer cascade.',
  ioAssignment: [
    { type: 'input', address: 'I0.0', label: 'Start Button' },
    { type: 'input', address: 'I0.1', label: 'Stop Button' },
    { type: 'input', address: 'I0.2', label: 'Night Mode Switch' },
    { type: 'output', address: 'Q0.0', label: 'Red Light' },
    { type: 'output', address: 'Q0.1', label: 'Yellow Light' },
    { type: 'output', address: 'Q0.2', label: 'Green Light' },
    { type: 'output', address: 'Q0.3', label: 'Night Mode Blink' },
  ],
  questions: [
    {
      id: 'tl_q1',
      title: 'Start Sequence',
      description: 'Buat ladder untuk memulai sequence lampu saat start (I0.0) ditekan.',
      hint: 'Gunakan latch untuk menyimpan status running',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'M0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'coil', address: 'M0.0', rung: 0, position: 3 },
      ],
      maxRungs: 1,
    },
    {
      id: 'tl_q2',
      title: 'Red Light ON',
      description: 'Lampu merah (Q0.0) ON saat system running (M0.0).',
      hint: 'Kontak NO (M0.0) mengaktifkan Q0.0',
      expectedAnswer: [
        { type: 'contact_no', address: 'M0.0', rung: 1, position: 0 },
        { type: 'coil', address: 'Q0.0', rung: 1, position: 1 },
      ],
      maxRungs: 2,
    },
    {
      id: 'tl_q3',
      title: 'Timer 1 - Red Duration',
      description: 'Tambahkan timer T0 (30 detik) untuk durasi lampu merah.',
      hint: 'M0.0 mengaktifkan timer T0',
      expectedAnswer: [
        { type: 'contact_no', address: 'M0.0', rung: 2, position: 0 },
        { type: 'timer_ton', address: 'T0', rung: 2, position: 1 },
      ],
      maxRungs: 2,
    },
    {
      id: 'tl_q4',
      title: 'Green Light After Red',
      description: 'Lampu hijau (Q0.2) ON setelah timer T0 done.',
      hint: 'Kontak NO (T0) mengaktifkan Q0.2',
      expectedAnswer: [
        { type: 'contact_no', address: 'T0', rung: 3, position: 0 },
        { type: 'contact_nc', address: 'T1', rung: 3, position: 1 },
        { type: 'coil', address: 'Q0.2', rung: 3, position: 2 },
      ],
      maxRungs: 3,
    },
    {
      id: 'tl_q5',
      title: 'Timer 2 - Green Duration',
      description: 'Tambahkan timer T1 (25 detik) untuk durasi lampu hijau.',
      hint: 'T0 mengaktifkan timer T1',
      expectedAnswer: [
        { type: 'contact_no', address: 'T0', rung: 4, position: 0 },
        { type: 'timer_ton', address: 'T1', rung: 4, position: 1 },
      ],
      maxRungs: 4,
    },
    {
      id: 'tl_q6',
      title: 'Yellow Light',
      description: 'Lampu kuning (Q0.1) ON setelah T1 done selama 5 detik (T2).',
      hint: 'T1 mengaktifkan T2, kontak NO (T1) + NC (T2) = Q0.1',
      expectedAnswer: [
        { type: 'contact_no', address: 'T1', rung: 5, position: 0 },
        { type: 'contact_nc', address: 'T2', rung: 5, position: 1 },
        { type: 'coil', address: 'Q0.1', rung: 5, position: 2 },
      ],
      maxRungs: 5,
    },
    {
      id: 'tl_q7',
      title: 'Loop Sequence',
      description: 'Buat sequence berulang: setelah T2 done, reset ke awal.',
      hint: 'Gunakan kontak NC (T2) untuk memutus M0.0 dan restart',
      expectedAnswer: [
        { type: 'contact_no', address: 'T2', rung: 6, position: 0 },
        { type: 'contact_nc', address: 'M0.0', rung: 6, position: 1 },
        { type: 'coil', address: 'M0.0', rung: 6, position: 2 },
      ],
      maxRungs: 6,
    },
    {
      id: 'tl_q8',
      title: 'Night Mode',
      description: 'Saat night mode (I0.2), lampu kuning berkedip. Gunakan counter CTU.',
      hint: 'Counter CTU untuk blinking effect',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.2', rung: 7, position: 0 },
        { type: 'counter_ctu', address: 'C0', rung: 7, position: 1 },
      ],
      maxRungs: 7,
    },
    {
      id: 'tl_q9',
      title: 'Stop Sequence',
      description: 'Stop (I0.1) harus mematikan semua lampu dan timer.',
      hint: 'I0.1 memutus M0.0 yang menjadi sumber semua output',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'M0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'coil', address: 'M0.0', rung: 0, position: 3 },
      ],
      maxRungs: 1,
    },
    {
      id: 'tl_q10',
      title: 'Full Traffic Light',
      description: 'Buat ladder lengkap: start/stop, 3 lampu dengan timer cascade, loop.',
      hint: 'Gabungkan: M0.0 (running), T0/T1/T2 (timers), Q0.0/Q0.1/Q0.2 (lights)',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'M0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'coil', address: 'M0.0', rung: 0, position: 3 },
        { type: 'contact_no', address: 'M0.0', rung: 1, position: 0 },
        { type: 'contact_nc', address: 'T0', rung: 1, position: 1 },
        { type: 'coil', address: 'Q0.0', rung: 1, position: 2 },
        { type: 'contact_no', address: 'T0', rung: 2, position: 0 },
        { type: 'contact_nc', address: 'T1', rung: 2, position: 1 },
        { type: 'coil', address: 'Q0.2', rung: 2, position: 2 },
        { type: 'contact_no', address: 'T1', rung: 3, position: 0 },
        { type: 'contact_nc', address: 'T2', rung: 3, position: 1 },
        { type: 'coil', address: 'Q0.1', rung: 3, position: 2 },
      ],
      maxRungs: 4,
    },
  ],
};

export const conveyorCase: CaseStudy = {
  id: 'conveyor',
  title: 'Conveyor System',
  description: 'Sistem conveyor dengan sensor dan interlock. Pelajari material handling dan safety interlocks.',
  ioAssignment: [
    { type: 'input', address: 'I0.0', label: 'Start Button' },
    { type: 'input', address: 'I0.1', label: 'Stop Button' },
    { type: 'input', address: 'I0.2', label: 'Sensor A (Entry)' },
    { type: 'input', address: 'I0.3', label: 'Sensor B (Exit)' },
    { type: 'input', address: 'I0.4', label: 'Emergency Stop' },
    { type: 'output', address: 'Q0.0', label: 'Conveyor Motor A' },
    { type: 'output', address: 'Q0.1', label: 'Conveyor Motor B' },
    { type: 'output', address: 'Q0.2', label: 'Alarm' },
  ],
  questions: [
    {
      id: 'cv_q1',
      title: 'Conveyor A Start',
      description: 'Buat ladder untuk menyalakan conveyor A (Q0.0) dengan start/stop.',
      hint: 'Konfigurasi start-stop-latch dasar',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 3 },
      ],
      maxRungs: 1,
    },
    {
      id: 'cv_q2',
      title: 'Conveyor B Interlock',
      description: 'Conveyor B (Q0.1) hanya boleh ON jika Conveyor A (Q0.0) sudah ON.',
      hint: 'Tambahkan kontak NO (Q0.0) di rung Conveyor B',
      expectedAnswer: [
        { type: 'contact_no', address: 'Q0.0', rung: 1, position: 0 },
        { type: 'contact_no', address: 'I0.0', rung: 1, position: 1 },
        { type: 'contact_no', address: 'Q0.1', rung: 1, position: 2 },
        { type: 'contact_nc', address: 'I0.1', rung: 1, position: 3 },
        { type: 'coil', address: 'Q0.1', rung: 1, position: 4 },
      ],
      maxRungs: 2,
    },
    {
      id: 'cv_q3',
      title: 'Sensor Auto Start',
      description: 'Conveyor A otomatis ON saat sensor A (I0.2) mendeteksi material.',
      hint: 'Sensor I0.2 menggantikan tombol start',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.2', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 3 },
      ],
      maxRungs: 1,
    },
    {
      id: 'cv_q4',
      title: 'Auto Stop at Sensor B',
      description: 'Conveyor A otomatis OFF saat sensor B (I0.3) mendeteksi material.',
      hint: 'Gunakan kontak NC (I0.3) untuk stop',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.2', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.3', rung: 0, position: 2 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 3 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 4 },
      ],
      maxRungs: 1,
    },
    {
      id: 'cv_q5',
      title: 'Emergency Stop',
      description: 'E-Stop (I0.4) harus mematikan semua conveyor segera.',
      hint: 'Tambahkan kontak NC (I0.4) di semua rung',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'contact_nc', address: 'I0.4', rung: 0, position: 3 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 4 },
      ],
      maxRungs: 1,
    },
    {
      id: 'cv_q6',
      title: 'Alarm Activation',
      description: 'Alarm (Q0.2) aktif saat E-Stop ditekan.',
      hint: 'Kontak NO (I0.4) mengaktifkan alarm',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.4', rung: 2, position: 0 },
        { type: 'coil', address: 'Q0.2', rung: 2, position: 1 },
      ],
      maxRungs: 2,
    },
    {
      id: 'cv_q7',
      title: 'Sequential Start Delay',
      description: 'Conveyor B baru ON 5 detik setelah Conveyor A ON. Gunakan timer.',
      hint: 'Timer TON diaktifkan oleh Q0.0, output timer mengaktifkan Q0.1',
      expectedAnswer: [
        { type: 'contact_no', address: 'Q0.0', rung: 1, position: 0 },
        { type: 'timer_ton', address: 'T0', rung: 1, position: 1 },
        { type: 'contact_no', address: 'T0', rung: 2, position: 0 },
        { type: 'coil', address: 'Q0.1', rung: 2, position: 1 },
      ],
      maxRungs: 2,
    },
    {
      id: 'cv_q8',
      title: 'Material Counter',
      description: 'Hitung jumlah material yang lewat sensor B. Gunakan counter CTU.',
      hint: 'Sensor B (I0.3) increment counter C0',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.3', rung: 3, position: 0 },
        { type: 'counter_ctu', address: 'C0', rung: 3, position: 1 },
      ],
      maxRungs: 3,
    },
    {
      id: 'cv_q9',
      title: 'Reverse Interlock',
      description: 'Conveyor A TIDAK boleh ON jika Conveyor B OFF (harus berurutan).',
      hint: 'Tambahkan kontak NO (Q0.1) sebagai syarat Q0.0',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_no', address: 'Q0.1', rung: 0, position: 2 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 3 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 4 },
      ],
      maxRungs: 1,
    },
    {
      id: 'cv_q10',
      title: 'Full Conveyor System',
      description: 'Buat ladder lengkap: sequential start, sensor control, E-stop, alarm.',
      hint: 'Gabungkan: Q0.0 (conveyor A), Q0.1 (conveyor B dengan delay), Q0.2 (alarm), I0.4 (E-stop)',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.1', rung: 0, position: 2 },
        { type: 'contact_nc', address: 'I0.4', rung: 0, position: 3 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 4 },
        { type: 'contact_no', address: 'Q0.0', rung: 1, position: 0 },
        { type: 'timer_ton', address: 'T0', rung: 1, position: 1 },
        { type: 'contact_no', address: 'T0', rung: 2, position: 0 },
        { type: 'contact_nc', address: 'I0.4', rung: 2, position: 1 },
        { type: 'coil', address: 'Q0.1', rung: 2, position: 2 },
        { type: 'contact_no', address: 'I0.4', rung: 3, position: 0 },
        { type: 'coil', address: 'Q0.2', rung: 3, position: 1 },
      ],
      maxRungs: 4,
    },
  ],
};

export const tankLevelCase: CaseStudy = {
  id: 'tank_level',
  title: 'Tank Level Control',
  description: 'Sistem kontrol level tangki dengan pump otomatis. Pelajari level control dan pump protection.',
  ioAssignment: [
    { type: 'input', address: 'I0.0', label: 'Auto Mode Switch' },
    { type: 'input', address: 'I0.1', label: 'Low Level Sensor' },
    { type: 'input', address: 'I0.2', label: 'High Level Sensor' },
    { type: 'input', address: 'I0.3', label: 'Manual Start' },
    { type: 'input', address: 'I0.4', label: 'Manual Stop' },
    { type: 'output', address: 'Q0.0', label: 'Inlet Pump' },
    { type: 'output', address: 'Q0.1', label: 'Low Level Alarm' },
    { type: 'output', address: 'Q0.2', label: 'High Level Alarm' },
  ],
  questions: [
    {
      id: 'tl_q1',
      title: 'Manual Pump Control',
      description: 'Buat ladder untuk menyalakan pump (Q0.0) secara manual dengan start/stop.',
      hint: 'Konfigurasi start-stop-latch',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.3', rung: 0, position: 0 },
        { type: 'contact_no', address: 'Q0.0', rung: 0, position: 1 },
        { type: 'contact_nc', address: 'I0.4', rung: 0, position: 2 },
        { type: 'coil', address: 'Q0.0', rung: 0, position: 3 },
      ],
      maxRungs: 1,
    },
    {
      id: 'tl_q2',
      title: 'Auto Mode Selection',
      description: 'Pump hanya ON di auto mode (I0.0) saat level rendah (I0.1).',
      hint: 'I0.0 DAN I0.1 mengaktifkan Q0.0',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 1, position: 0 },
        { type: 'contact_no', address: 'I0.1', rung: 1, position: 1 },
        { type: 'coil', address: 'Q0.0', rung: 1, position: 2 },
      ],
      maxRungs: 1,
    },
    {
      id: 'tl_q3',
      title: 'Auto Stop at High Level',
      description: 'Pump otomatis OFF saat high level (I0.2) tercapai.',
      hint: 'Tambahkan kontak NC (I0.2) untuk stop pump',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 1, position: 0 },
        { type: 'contact_no', address: 'I0.1', rung: 1, position: 1 },
        { type: 'contact_nc', address: 'I0.2', rung: 1, position: 2 },
        { type: 'coil', address: 'Q0.0', rung: 1, position: 3 },
      ],
      maxRungs: 1,
    },
    {
      id: 'tl_q4',
      title: 'Low Level Alarm',
      description: 'Alarm low level (Q0.1) aktif saat sensor low (I0.1) ON.',
      hint: 'I0.1 mengaktifkan Q0.1',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.1', rung: 2, position: 0 },
        { type: 'coil', address: 'Q0.1', rung: 2, position: 1 },
      ],
      maxRungs: 2,
    },
    {
      id: 'tl_q5',
      title: 'High Level Alarm',
      description: 'Alarm high level (Q0.2) aktif saat sensor high (I0.2) ON.',
      hint: 'I0.2 mengaktifkan Q0.2',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.2', rung: 3, position: 0 },
        { type: 'coil', address: 'Q0.2', rung: 3, position: 1 },
      ],
      maxRungs: 3,
    },
    {
      id: 'tl_q6',
      title: 'Pump Latching in Auto',
      description: 'Pump tetap ON di auto mode meskipun level naik (latching), stop hanya di high level.',
      hint: 'Gunakan latch Q0.0 dengan stop condition I0.2',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 1, position: 0 },
        { type: 'contact_no', address: 'I0.1', rung: 1, position: 1 },
        { type: 'contact_no', address: 'Q0.0', rung: 1, position: 2 },
        { type: 'contact_nc', address: 'I0.2', rung: 1, position: 3 },
        { type: 'coil', address: 'Q0.0', rung: 1, position: 4 },
      ],
      maxRungs: 1,
    },
    {
      id: 'tl_q7',
      title: 'Pump Delay Start',
      description: 'Pump delay 3 detik setelah low level terdeteksi (anti-cycling).',
      hint: 'Timer TON antara sensor dan pump',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 1, position: 0 },
        { type: 'contact_no', address: 'I0.1', rung: 1, position: 1 },
        { type: 'timer_ton', address: 'T0', rung: 1, position: 2 },
        { type: 'contact_no', address: 'T0', rung: 2, position: 0 },
        { type: 'coil', address: 'Q0.0', rung: 2, position: 1 },
      ],
      maxRungs: 2,
    },
    {
      id: 'tl_q8',
      title: 'Pump Run Timer',
      description: 'Pump otomatis OFF setelah running 10 menit (proteksi). Gunakan timer.',
      hint: 'Timer TON (T1) diaktifkan saat pump ON, kontak NC T1 memutus pump',
      expectedAnswer: [
        { type: 'contact_no', address: 'Q0.0', rung: 3, position: 0 },
        { type: 'timer_ton', address: 'T1', rung: 3, position: 1 },
      ],
      maxRungs: 3,
    },
    {
      id: 'tl_q9',
      title: 'Alarm Latching',
      description: 'Alarm high level (Q0.2) tetap ON sampai direset, meskipun level turun.',
      hint: 'Gunakan latch untuk alarm dengan reset button',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.2', rung: 4, position: 0 },
        { type: 'contact_no', address: 'Q0.2', rung: 4, position: 1 },
        { type: 'contact_nc', address: 'I0.4', rung: 4, position: 2 },
        { type: 'coil', address: 'Q0.2', rung: 4, position: 3 },
      ],
      maxRungs: 4,
    },
    {
      id: 'tl_q10',
      title: 'Full Tank Level Control',
      description: 'Buat ladder lengkap: auto mode, pump control dengan delay, alarms, proteksi.',
      hint: 'Gabungkan: I0.0 (auto), I0.1 (low), I0.2 (high), T0 (delay), Q0.0 (pump), Q0.1/Q0.2 (alarms)',
      expectedAnswer: [
        { type: 'contact_no', address: 'I0.0', rung: 0, position: 0 },
        { type: 'contact_no', address: 'I0.1', rung: 0, position: 1 },
        { type: 'timer_ton', address: 'T0', rung: 0, position: 2 },
        { type: 'contact_no', address: 'T0', rung: 1, position: 0 },
        { type: 'contact_nc', address: 'I0.2', rung: 1, position: 1 },
        { type: 'coil', address: 'Q0.0', rung: 1, position: 2 },
        { type: 'contact_no', address: 'I0.1', rung: 2, position: 0 },
        { type: 'coil', address: 'Q0.1', rung: 2, position: 1 },
        { type: 'contact_no', address: 'I0.2', rung: 3, position: 0 },
        { type: 'coil', address: 'Q0.2', rung: 3, position: 1 },
      ],
      maxRungs: 4,
    },
  ],
};

export const allCases: CaseStudy[] = [
  dolMotorCase,
  starDeltaCase,
  trafficLightCase,
  conveyorCase,
  tankLevelCase,
];
